name: Deploy
on:
  workflow_dispatch:


name: Azure Login
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ variable.AZURE_RESOURCE_GROUP_NAME }}
        template: ./ARM-Templates/container-webapp-template.json