name: Deploy to Azure

on: 
  workflow_dispatch: 
    inputs: 
      environment: 
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
        templateLocation: "Embedded"  
        template: "InfrastructureAsCode/main.bicep"  
        #csmParametersFile: "/workspaces/wth-team1/InfrastructureAsCode/parameter.json"