name: Azure Login
on: 
 push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
jobs: 
  Windows-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}
          
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCEGROUP }}
          template: ./InfrastructureAsCode/main.bicep