name: Azure Login
on: 
 push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
jobs: 
  Windows-latest:
    runs-on: windows-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}
          enable-AzPSSession: true

      - name: Get resource group with PowerShell action
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
          azPSVersion: "latest"

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCEGROUP }}
          template: ./InfrastructureAsCode/main.bicep