name: My Workflow

on: 
  workflow_dispatch:
  issues:
    types: [opened]

env:
  MY_ENV_VAR: "This is my environment variable"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: echo "This is step 1"
    - name: Step 2
      run: echo ${{ env.MY_ENV_VAR }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
     steps:
  - name: My GitHub Action
    uses: owner/repo@version
    with:
      input_name: ${{ env.MY_ENV_VAR }}